config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :links

  get '/satelitalreports/operativos' => 'links#index_estado'
  get '/satelitalreports/capacidades' => 'links#index_capacidad'

  resource :satelitalreports, only: [:show] do 
    resources :operativos, only: [:show]
    resources :capacidades, only: [:show]
    resources :graficos, only: [:show]
  end

=begin

    get "/sites"          index
    post "/sites"         create
    delete "/sites"       delete
    get "/sites/:id"      show
    get "/sites/new"      new
    get "/sites/:id/edit" edit
    get "/sites/:id"      update
    put "/sites/:id"      update
=end

  root 'welcome#index'

end

app/models/link.rb
class Link < ActiveRecord::Base

	belongs_to :user
	
	validates :Provedor_Enlace, presence: true
	validates :Red_Satelital, presence: true
	validates :Razon_Social, presence: true
	validates :Codigo, presence: true
	validates :Site, presence: true
	validates :Nombre_Enlace, presence: true
	validates :CID, presence: true, uniqueness: true
	validates :Sector_Red, presence: true
	validates :Estado, presence: true
	validates :Satelite, presence: true
	validates :Tipo, presence: true
	validates :Capacidad_Mbps, presence: true
	validates :Capacidad_Mhz, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index, :index_estado]
  before_action :set_link, except: [:index, :index_estado, :new, :create]
  #GET /links
  def index
    @links = Link.all
  end

  #GET /links/:id
  def show
    
  end

  #GET /links/new
  def new
    @link = Link.new
  end

  #POST /links
  def create
    @link = current_user.links.new(link_params)
    if @link.save
      redirect_to @link
    else
      render :new
    end
  end

  #UPDATE /links/:id
  def destroy
    @link.destroy
    redirect_to links_path
  end

  #UPDATE /links/:id
  def edit
    
  end

  def index_estado
    @index_estado = Link.where(Estado: "Operativo")
  end

  def update
    if @link.update(link_params)
      redirect_to @link
    else
      render :edit
    end
  end

  private

  def set_link
      @link = Link.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:Provedor_Enlace,:Red_Satelital,:Razon_Social,:Codigo,:Site,
                  :Nombre_Enlace,:CID,:Sector_Red,:Estado,:Satelite,:Tipo,:Capacidad_Mbps,:Capacidad_Mhz)
  end
end

app/controllers/operativos_controller.rb
class OperativosController < ApplicationController

  def show

  end

end

app/controllers/satelitalreports_controller.rb
class SatelitalreportsController < ApplicationController

  def show

  end

end

app/controllers/satelitals_controller.rb
class SatelitalsController < ApplicationController

  def index
    @satelitals = Satelital.all
    unless Satelital.last == nil
      @table = Satelital.last[:satelital_array]
    end
  end

  def show
    @satelital = Satelital.find(params[:satelital][:id])
    rescue => e
     flash[:error] = "Escoja un reporte válido."
     redirect_to ppmreports_ppmroutes_path
  end

  def create
    @satelitals = Satelital.all
    @satelital = Satelital.create(:satelital_array => Satelital.capacidad_table)
    if @satelital.save
      @satelital.created_at.in_time_zone('Eastern Time (US & Canada)')
      flash[:notice] = "Reporte actualizado y almacenado."
      redirect_to '/satelitalreports/satelitals'
      if @satelitals.count > 100
        @satelitals.first.delete
      end
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReporteSatelital</title>
  <link href='https://fonts.googleapis.com/css?family=Raleway:500,900,200' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body data-no-turbolinks="true">
	<%= render "partials/navigation"%>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
    <% @link.errors.full_messages.each do |message| %>
      <div class="be-red white field top-space">
        * <%= message %>
      </div>
    <%end%>
    <div class="field">
      <%= f.text_field :Provedor_Enlace, placeholder: "Escriba el Proveedor del Enlace", class:"form-control-comm" %>
    </div>
    <div class="field">
      <%= f.text_field :Red_Satelital, placeholder: "Escriba La Red del Enlace", class:"form-control-comm" %>
    </div>
    <div class="field">
      <%= f.text_field :Razon_Social, placeholder: "Escriba la Razón Social", class:"form-control-comm" %>
    </div>
    <div class="field">
      <%= f.text_field :Codigo, placeholder: "Escriba el Código", class:"form-control-comm" %>
    </div>
    <div class="field">
      <%= f.text_field :Site, placeholder: "Escriba el Site", class:"form-control-comm"%>
    </div>
    <div class="field">
      <%= f.text_field :Nombre_Enlace, placeholder: "Escriba el Nombre del Enlace", class:"form-control-comm" %>
    </div>
    <div class="field">
      <%= f.text_field :CID, placeholder: "Escriba el CID", class:"form-control-comm" %>
    </div>
    <div class="field">
      <%= f.text_field :Sector_Red, placeholder: "Escriba el Sector de Red", class:"form-control-comm" %>
    </div>
    <div class="field">
      <%= f.text_field :Estado, placeholder: "Escriba el Estado del Enlace", class:"form-control-comm" %>
    </div>
    <div class="field">
      <%= f.text_field :Satelite, placeholder: "Escriba el Satélite", class:"form-control-comm" %>
    </div>
    <div class="field">
      <%= f.text_field :Tipo, placeholder: "Escriba el Tipo del Enlace", class:"form-control-comm" %>
    </div>
    <div class="field">
      <%= f.number_field :Capacidad_Mbps, placeholder: "Escriba el Capacidad en Kbps", class:"form-control-comm" %>
    </div>
    <div class="field">
      <%= f.number_field :Capacidad_Mhz, placeholder: "Escriba el Capacidad en Mhz", class:"form-control-comm", :step => 'any' %>
    </div>
    <div class="field">
      <%= f.submit "Guardar", class:"btn be-red white" %>
    </div>
  <%end%>

app/views/links/edit.html.erb
<div style="width:95%;margin:0 auto;">
	<h3>Modificar Enlace Satelital con CID <%= @link.CID %></h3>
	<h4><%=link_to "Volver", link_path, class:"btn white be-red top-space "%></h4>
	<%= render "form", name: "Modificar" %>
</div>

app/views/links/index.html.erb
<div class="row center-xs">
  <div class="col-md-10">
    <div class="text-left">
      <h3>Histórico de Enlaces Satelitales</h3>
      <h4><%=link_to "Crear", new_link_path(@link), class:"btn white be-red top-space "%></h4>
    </div>
  </div>
</div>

<div style="width:100%;margin:0 auto;">
  <table style="width:100%">
        <tr>
          <th>Item</th>
          <th>Provedor de Enlace</th>
          <th>Red_Satelital</th>
          <th>Razon_Social</th>
          <th>Código</th>
          <th>Site</th>
          <th>Nombre de Enlace</th>
          <th>CID</th>
          <th>Sector de Red</th>
          <th>Estado</th>
          <th>Satélite</th>
          <th>Tipo de Enlace</th>
          <th>Capacidad (Kbps)</th>
          <th>Capacidad (Mhz)</th>
        </tr>
        <% i=0 %>
        <% @links.each do |link| %>
          <tr>
            <% i+=1 %>
            <td><%= link_to i, link %></td>
            <td><%= link.Provedor_Enlace %></td>
            <td><%= link.Red_Satelital %></td>
            <td><%= link.Razon_Social %></td>
            <td><%= link.Codigo %></td>
            <td><%= link.Site %></td>
            <td><%= link.Nombre_Enlace %></td>
            <td><%= link_to link.CID, link %></td>
            <td><%= link.Sector_Red %></td>
            <td><%= link.Estado %></td>
            <td><%= link.Satelite %></td>
            <td><%= link.Tipo %></td>
            <td><%= link.Capacidad_Mbps %></td>
            <td><%= link.Capacidad_Mhz %></td>
          </tr>
        <% end %>
    </table>
  </div>
</div>

app/views/links/index_estado.html.erb
<div class="row center-xs">
  <div class="col-md-10">
		<div class="text-left">
			<h3>Enlaces Satelitales Operativos</h3>
			<h4><%=link_to "Volver", satelitalreports_path, class:"btn white be-blue top-space "%></h4>
		</div>
	</div>
</div>

<div style="width:100%;margin:0 auto;">
	<table style="width:100%">
		<tr>
			<th>Item</th>
			<th>Provedor de Enlace</th>
			<th>Red_Satelital</th>
			<th>Razon_Social</th>
			<th>Código</th>
			<th>Site</th>
			<th>Nombre de Enlace</th>
			<th>CID</th>
			<th>Sector de Red</th>
			<th>Satélite</th>
			<th>Tipo de Enlace</th>
			<th>Capacidad (Kbps)</th>
			<th>Capacidad (Mhz)</th>
		</tr>
		<% i=0 %>
		<% @index_estado.each do |link| %>
		<tr>
			<% i+=1 %>
			<td><%= i %></td>
			<td><%= link.Provedor_Enlace %></td>
			<td><%= link.Red_Satelital %></td>
			<td><%= link.Razon_Social %></td>
			<td><%= link.Codigo %></td>
			<td><%= link.Site %></td>
			<td><%= link.Nombre_Enlace %></td>
			<td><%= link.CID %></td>
			<td><%= link.Sector_Red %></td>
			<td><%= link.Satelite %></td>
			<td><%= link.Tipo %></td>
			<td><%= link.Capacidad_Mbps %></td>
			<td><%= link.Capacidad_Mhz %></td>
		</tr>
		<% end %>
	</table>
</div>

app/views/links/new.html.erb
<div style="width:95%;margin:0 auto;">
	<h3>Crear nuevo Enlace Satelital</h3>
	<h4><%=link_to "Volver", links_path, class:"btn white be-red top-space "%></h4>
	<%= render "form"%>
</div>

app/views/links/show.html.erb
<div class="row center-xs">
  <div class="col-md-10">
		<div class="text-left">
			<h3>Enlace del CID <%= @link.CID %></h3>
			<% unless @link.user.nil? %>
				<p>
				Creado por: <%= @link.user.email %>
				</p>
			<%end%>
			<h4><%=link_to "Volver", links_path, class:"btn white be-red top-space "%></h4>
		</div>
	</div>
</div>


<div style="width:100%;margin:0 auto;">
	<table style="width:100%">
			<tr>
				<th>Provedor de Enlace</th>
				<th>Red Satelital</th>
				<th>Razon Social</th>
				<th>Código</th>
				<th>Site</th>
				<th>Nombre de Enlace</th>
				<th>CID</th>
				<th>Sector de Red</th>
				<th>Estado</th>
				<th>Satélite</th>
				<th>Tipo de Enlace</th>
				<th>Capacidad (Kbps)</th>
				<th>Capacidad (Mhz)</th>
			</tr>
			<tr>
				<td><%= @link.Provedor_Enlace %></td>
				<td><%= @link.Red_Satelital %></td>
				<td><%= @link.Razon_Social %></td>
				<td><%= @link.Codigo %></td>
				<td><%= @link.Site %></td>
				<td><%= @link.Nombre_Enlace %></td>
				<td><%= @link.CID %></td>
				<td><%= @link.Sector_Red %></td>
				<td><%= @link.Estado %></td>
				<td><%= @link.Satelite %></td>
				<td><%= @link.Tipo %></td>
				<td><%= @link.Capacidad_Mbps %></td>
				<td><%= @link.Capacidad_Mhz %></td>
			</tr>
	</table>
</div>

<div class="row center-xs">
  <div class="col-md-10">
		<div class="text-left">
			<h4><%=link_to "Modificar", edit_link_path(@link), class:"btn white be-red" %></h4>
			<h4> <%=link_to "Eliminar", @link, method: :delete, class:"btn white be-red" %></h4>
		</div>
	</div>
</div>

app/views/operativos/show.html.erb
<div class="row center-xs">
  <div class="col-xs-8 col-md-11">
		<div class="text-left">
			<h3>Enlaces Satelitales Operativos</h3>
		</div>
	</div>
</div>

<div style="width:100%;margin:0 auto; h3">
	<table style="width:100%" id="t01">
		<tr>
			<th>Item</th>
			<th>Provedor de Enlace</th>
			<th>Red_Satelital</th>
			<th>Razon_Social</th>
			<th>Código</th>
			<th>Site</th>
			<th>Nombre de Enlace</th>
			<th>CID</th>
			<th>Sector de Red</th>
			<th>Satélite</th>
			<th>Tipo de Enlace</th>
			<th>Capacidad (Kbps)</th>
			<th>Capacidad (Mhz)</th>
		</tr>
		<% i=0 %>
		<% @index_estado.each do |link| %>
		<tr>
			<% i+=1 %>
			<td><%= i %></td>
			<td><%= link.Provedor_Enlace %></td>
			<td><%= link.Red_Satelital %></td>
			<td><%= link.Razon_Social %></td>
			<td><%= link.Codigo %></td>
			<td><%= link.Site %></td>
			<td><%= link.Nombre_Enlace %></td>
			<td><%= link.CID %></td>
			<td><%= link.Sector_Red %></td>
			<td><%= link.Satelite %></td>
			<td><%= link.Tipo %></td>
			<td><%= link.Capacidad_Mbps %></td>
			<td><%= link.Capacidad_Mhz %></td>
		</tr>
		<% end %>
	</table>
</div>

app/views/partials/_navigation.html.erb
<header>
		<nav class="be-red white large-padding">
			<ul class="row center-xs middle-xs">
				<hi class="col-md">
					<h1 class="no-margin" id="logo"><%= link_to "Dashboard", root_path %></h1>
				</hi>
				<hi class="col-md">
					<%= link_to "Capacidad Satelital", links_path %>
				</hi>
				<hi class="col-md">
					<%= link_to "Reportes Satelital", satelitalreports_path %>
				</hi>
				<hi class="col-md">
					Información
				</hi>
				<% if user_signed_in? %>
					<hi class="col-md">
						<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
					</hi>
				<%else%>
				<hi class="col-md">
					<%= link_to "Iniciar sesión", new_user_session_path %>
				</hi>
				<hi class="col-md">
					<%= link_to "Crear usuario", new_user_registration_path %>
				</hi>
				<%end%>
			</ul>
		</nav>
</header>

app/views/satelitalreports/show.html.erb
<div class="row center-xs">
  <div class="col-md-10">
    <div class="text-left">
  		<h3>Reportes Satelital</h3>
  	</div>
	</div>
</div>

<div style="width:50%;margin:0 auto;">
	<table style="width:100%">
		<thead>
			<tr>
				<th>Nombre</th>
				<th>Descripción</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%=link_to "Operativos", satelitalreports_operativos_path%></td>
				<td>Enlaces Operativos</td>
			</tr>
			<tr>
				<td>Capacidades</td>
				<td>Distribución de Capacidades</td>
			</tr>
			<tr>
				<td>Graficos</td>
				<td>Reportes Gráficos</td>
			</tr>
		</tbody>
  </table>
  <h4><%=link_to "Volver", root_path, class:"btn white be-red" %></h4>
</div>

app/views/satelitals/index.html.erb
<div class="row">
  <div class="col-md-2">
    <div class="col-md-8">
      <h3>Capacidad de Enlaces Satelitales </h3>
      <h4><%=link_to "Actualizar", satelitalreports_satelitals_path,  method: :post, class:"btn white be-red top-space "%></h4>
      <h3 class:"btn">Actualizado</h3>
      <% unless Satelital.last == nil %>
      <h3 class:"btn">Ppmroute.last.created_at.strftime("%d/%m/%Y %H:%M:%S")</h3>
      <% else %>
      <h3 class:"btn">'-'</h3>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-2">
    <div class="col-md-8">
      <h4><%=link_to "Volver", satelitalreports_path, class:"float-left"%></h4>
      <div class:"float-rigth">
        <%=form_tag satelitalreports_satelital_path(:id), :method => :get do
        collection_select(:satelital, :id, Satelital.all, :id, :created_at, prompt: "10 Reportes anteriores"
        submit_tag "Consultar", :name => nil, class: 'btn btn-sm btn-info'%>
      </div>
    </div>
  </div>
</div>


<div class="row margin-top-00">
  <div class="col-md-2">
    <table style="width:100%">
    <thead>
      <tr>
        <th>Clientes</th>
        <th>Nº Enlaces</th>
        <th>Capac. (Kbps)</th>
        <th>Capac. (Mhz)</th>
      </tr>
    </thead>
    <tbody>
      <% unless Satelital.last == nil %>
        <% @table.map do |item| %>
          <tr>
            <td>AMERICA MOVIL PERU S.A.C.</td>
            <td><%= item.Provedor_Enlace %></td>
          </tr>
          <tr>
            <td>TELMEX PERU S.A.</td>
            <td>Distribución de Capacidades</td>
          </tr>
          <tr>
            <td>OTROS CLIENTES</td>
            <td>Reportes Gráficos</td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <h4><%=link_to "Volver", satelitalreports_path, class:"btn white be-blue top-space "%></h4>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>¡¡¡Pendiente agregar diagramas!!!</h1>